evmNetworkId: 100
#privateKeyEencrypted: "8LOO7qtMiqNxT-ygJEawyJyTs9Nay06xXmuJ0_jeyTTRopJ8iIFCckcCbW4S46eMdfQdTfCVjvtxQmt-HuOKkMjpjzwwxFB5OB8R47_Njyurg22LyDG4Kv5Vu11RqM8ia9pAAFQtLGdLczSYdbHuzA"
priceMultiplier: 1.5
issueCreatorMultiplier: 2
timeLabels:
  - name: "Time: <1 Hour"
  - name: "Time: <2 Hours"
  - name: "Time: <4 Hours"
  - name: "Time: <1 Day"
  - name: "Time: <1 Week"
priorityLabels:
  - name: "Priority: 1 (Normal)"
  - name: "Priority: 2 (Medium)"
  - name: "Priority: 3 (High)"
  - name: "Priority: 4 (Urgent)"
  - name: "Priority: 5 (Emergency)"
defaultLabels:
  - "Time: <1 Hour"
  - "Priority: 1 (Normal)"
paymentPermitMaxPrice: 1000
commentIncentives: true
maxConcurrentAssigns: 5
promotionComment: "<h6>If you've enjoyed your experience in the DevPool, we'd appreciate your support. Follow <a href='https://github.com/ubiquity'>Ubiquity on GitHub</a> and star <a href='https://github.com/ubiquity/devpool-directory'>this repo</a>. Your endorsement means the world to us and helps us grow!</h6><h6>We are excited to announce that the DevPool and UbiquiBot are now available to partners! Our ideal collaborators are globally distributed crypto-native organizations, who actively work on open source on GitHub, and excel in research & development. If you can introduce us to the repository maintainers in these types of companies, we have a special bonus in store for you!</h6>"
incentives:
  comment:
    issue:
      assignee: true
      creator: true
      default: true
    elements:
      code: 10
      img: 0
      li: 0
      a: 0
      blockquote: 0
    totals:
      word: 0.1
registerWalletWithVerification: false
assistivePricing: true
staleBountyTime: 1d
